"""Type replacement for id

Revision ID: 3d8beba4e55b
Revises: 5824bfe71c87
Create Date: 2026-09-23 16:57:34.409351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3d8beba4e55b'
down_revision: Union[str, Sequence[str], None] = '5824bfe71c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Пришлось переписать вручную
    op.drop_table('cities')
    op.create_table('cities',
        sa.Column('id', sa.Uuid(), primary_key=True),
        sa.Column('name', sa.String(256), nullable=False),
        sa.Column('country', sa.String(256), nullable=False),
        sa.Column('population', sa.Integer, nullable=False),
        sa.Column('created_at', sa.DateTime, server_default=sa.text("TIMEZONE('utc', now())")),
        sa.Column('updated_at', sa.DateTime, server_default=sa.text("TIMEZONE('utc', now())")),
        sa.Column('is_deleted', sa.Boolean, server_default=sa.text('false')),
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
