"""add onupdate for updated_at

Revision ID: 65be85898b9d
Revises: b4b6659a43ac
Create Date: 2026-09-29 14:45:32.023942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65be85898b9d'
down_revision: Union[str, Sequence[str], None] = 'b4b6659a43ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('cities', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('cities', 'is_deleted',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
